<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGXQUk3H\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGXQUk3H/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGXQUk3H.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGXQUk3H\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGXQUk3H\App_KernelDevDebugContainer([
    'container.build_hash' => 'GXQUk3H',
    'container.build_id' => '7f417842',
    'container.build_time' => 1705652122,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGXQUk3H');
