<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGK6CyCL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGK6CyCL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGK6CyCL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGK6CyCL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGK6CyCL\App_KernelDevDebugContainer([
    'container.build_hash' => 'GK6CyCL',
    'container.build_id' => 'b8e000b4',
    'container.build_time' => 1708463325,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGK6CyCL');
