<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNyJpqrO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNyJpqrO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNyJpqrO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNyJpqrO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNyJpqrO\App_KernelDevDebugContainer([
    'container.build_hash' => 'NyJpqrO',
    'container.build_id' => '38b0f49d',
    'container.build_time' => 1707847071,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNyJpqrO');
